### ISSUE TITLE
Review comments.

### ISSUE THREAD

**Issue by Fawke** [shivamadurai/movie-app-crud#1]
1. Favourites list is implemented but unable to create user defined collections.
2. Proper use of Bootstrap classes to improve UI/UX experience.
3. Javascript code should be broken down into services, views and controller layer.
4. Use redux for state maangement.
5. Configure webpack and eslint in your project. Jshint is fine, but there should be some command to run it.
6. Create a README.md file describing about the project, commands to build it and share some screenshots of the UI.

**Comment by Fawke** [comment]
Hey, are you closing this issue. I wanted to mark your assignment as completed.

**Comment by shivamadurai** [comment]
Updated with refactoring and state management codes
